# Generated by Django 3.0.1 on 2020-03-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='profile-photos'),
        ),
    ]
