# Generated by Django 3.0.1 on 2020-02-10 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='linkedfolder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fileshare.Folder'),
        ),
    ]
