# Generated by Django 3.0.1 on 2020-02-10 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0002_folder_linkedfolder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='linkedfolder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fileshare.Folder'),
        ),
    ]
