# Generated by Django 3.0.1 on 2020-03-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0005_auto_20200314_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.FileField(upload_to=''),
        ),
    ]
