# Generated by Django 3.0.1 on 2020-03-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0008_auto_20200314_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
