# Generated by Django 3.0.1 on 2020-03-18 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0009_auto_20200318_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='author',
        ),
    ]
