# Generated by Django 3.0.1 on 2020-03-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0010_remove_folder_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
