# Generated by Django 3.0.1 on 2020-03-21 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0013_folderupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FolderUpload',
        ),
    ]
